batch_size: 2
learning_rate: 0.0005
adam_b1: 0.8
adam_b2: 0.99
warmup_epochs: 10
seed: 1234
dense_channel: 64
compress_factor: 0.3
num_tsblocks: 4
beta: 2.0
sampling_rate: 16000
segment_size: 32000
n_fft: 400
hop_size: 100
win_size: 400
num_workers: 4
